# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96b02be758edf3f7246ffa05bc18da7817f6d0469c9458b5a35ca90e11925f648a79f1f16890b425866a0e24bd3706768ab998ef104f2ca8df396f7e9e522ed2

test:
  secret_key_base: 7b21dbfb38108218dc6b663c1a17474df0fddb2bdabb5e0219e1bc73650631eb43d4b35fcdaa6d0494c6b1719d79dfe2ef90f6a36ca0d045d2a3f984b2d4e90e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
